# Generated by Django 5.1.3 on 2024-12-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterModelOptions(
            name='frasemodel',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.RemoveField(
            model_name='autormodel',
            name='profesion',
        ),
        migrations.AddField(
            model_name='autormodel',
            name='profesion',
            field=models.ManyToManyField(to='App1.profesion', verbose_name='Profesión'),
        ),
    ]
